# $NetBSD$

DISTNAME=	rest-client-0.9.2
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	pedro@joyent.com
HOMEPAGE=	http://dev.ctor.org/httpclient
COMMENT=	Simple HTTP and REST client for Ruby inspired by Sinatra
LICENSE=        mit

# Intentionally releasing old version right now, do not submit.
#DEPENDS+=	${RUBY_PKGPREFIX}-mime-types>=1.16:../../mail/ruby-mime-types

GEM_BUILD=	gemspec

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
