# $NetBSD$

DISTNAME=	rest-client-1.6.7
CATEGORIES=	devel

MAINTAINER=	pedro@joyent.com
HOMEPAGE=	http://github.com/archiloque/rest-client
COMMENT=	Simple HTTP and REST client for Ruby inspired by Sinatra
LICENSE=        mit

DEPENDS+=	${RUBY_PKGPREFIX}-mime-types>=1.16:../../mail/ruby-mime-types

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
