# $NetBSD$

DISTNAME=	soap4r-1.5.8
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	pedro@joyent.com
HOMEPAGE=	http://dev.ctor.org/soap4r
COMMENT=	Implementation of SOAP 1.1 for Ruby
LICENSE=	ruby-license

DEPENDS+=	${RUBY_PKGPREFIX}-httpclient-[0-9]*:../../joyent/ruby-httpclient

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
