# $NetBSD$
#

DISTNAME=	build-essential-1.0
CATEGORIES=	devel meta-pkgs
MASTER_SITES=	# empty

MAINTAINER=	jperkin@joyent.com
HOMEPAGE=	http://www.joyent.com/
COMMENT=	Meta-package for essential build utilities

DEPENDS+=	autoconf-[0-9]*:../../devel/autoconf
DEPENDS+=	automake-[0-9]*:../../devel/automake
DEPENDS+=	binutils-[0-9]*:../../devel/binutils
DEPENDS+=	bison-[0-9]*:../../devel/bison
DEPENDS+=	gcc47-[0-9]*:../../lang/gcc47
DEPENDS+=	gmake-[0-9]*:../../devel/gmake
DEPENDS+=	libtool-[0-9]*:../../devel/libtool
DEPENDS+=	m4-[0-9]*:../../devel/m4
DEPENDS+=	patch-[0-9]*:../../devel/patch
DEPENDS+=	scmgit-[0-9]*:../../devel/scmgit

META_PACKAGE=	yes

.include "../../mk/bsd.pkg.mk"
