# $NetBSD$

PKGNAME=	zabbix24-${VER}

CONFLICTS+=     zabbix22

DEPENDS+=       zabbix24-agent>=${PKGVERSION_NOREV}:../../joyent/zabbix24-agent

META_PACKAGE=   yes

.include "Makefile.common"

.include "../../mk/bsd.pkg.mk"
