# $NetBSD$
#

DISTNAME=	Scalar-Util-Numeric-0.22
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	devel joyent
MASTER_SITES=	http://search.cpan.org/CPAN/authors/id/C/CH/CHOCOLATE/

MAINTAINER=	filip@joyent.com
HOMEPAGE=	http://search.cpan.org/~chocolate/Scalar-Util-Numeric-0.22/
COMMENT=	Numeric tests for Perl datatypes

PERL5_PACKLIST=	auto/Scalar/Util/Numeric/.packlist

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
