# $NetBSD$
#

DISTNAME=	Unicode-Japanese-0.46
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	textproc joyent
MASTER_SITES=	http://search.cpan.org/CPAN/authors/id/H/HI/HIO/

MAINTAINER=	filip@joyent.com
HOMEPAGE=	http://search.cpan.org/CPAN/authors/id/H/HI/HIO/
COMMENT=	Convert encoding of japanese text

PERL5_PACKLIST=	auto/Unicode/Japanese/.packlist

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
