# $NetBSD$

DISTNAME=	fast_xs-0.7.3
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME:S/_/-/}
MASTER_SITES=	http://rubyforge.org/frs/download.php/61355/
EXTRACT_SUFX=	.gem
CATEGORIES=	www

MAINTAINER=	filip@joyent.com
HOMEPAGE=	http://bogonips.org/fast_xs/
COMMENT=	Provides C extensions for escaping text
LICENSE=	mit

GEM_BUILD=	gemspec

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
