# $NetBSD$

DISTNAME=	scmgit-docs-2.0
CATEGORIES=	meta-pkgs
MASTER_SITES=	# empty
DISTFILES=	# empty

MAINTAINER=	pkgsrc@joyent.com
COMMENT=	Meta-package for old 'scmgit-docs', use 'git-docs' instead

META_PACKAGE=	yes

DEPENDS+=	git-docs-[0-9]*:../../devel/git-docs

.include "../../mk/bsd.pkg.mk"
