# $NetBSD$

DISTNAME=	scmgit-gitk-2.0
CATEGORIES=	meta-pkgs
MASTER_SITES=	# empty
DISTFILES=	# empty

MAINTAINER=	pkgsrc@joyent.com
COMMENT=	Meta-package for old 'scmgit-gitk', use 'git-gitk' instead

META_PACKAGE=	yes

DEPENDS+=	git-gitk-[0-9]*:../../devel/git-gitk

.include "../../mk/bsd.pkg.mk"
