# $NetBSD: Makefile,v 1.7 2006/06/04 16:26:52 joerg Exp $

MODNAME=		mailparse
PECL_VERSION=		2.1.6
CATEGORIES+=		mail
COMMENT=		PHP extension for email message manipulation

.include "../../lang/php/ext.mk"
.include "../../converters/php-mbstring/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
