# $NetBSD$

DISTNAME=	bunny-0.6.0
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	net

MAINTAINER=	pedro@joyent.com
HOMEPAGE=	http://wiki.github.com/celldee/bunny
COMMENT=	Synchronous Ruby AMQP client
LICENSE=        mit


GEM_BUILD=	gemspec

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
