# $NetBSD$

DISTNAME=	scmgit-2.0
CATEGORIES=	meta-pkgs
MASTER_SITES=	# empty
DISTFILES=	# empty

MAINTAINER=	pkgsrc@joyent.com
COMMENT=	Meta-package for old 'scmgit', use 'git' instead

META_PACKAGE=	yes

DEPENDS+=	git-[0-9]*:../../devel/git

.include "../../mk/bsd.pkg.mk"
