# $NetBSD$

MODNAME=		oauth
PECL_VERSION=		1.2.3
CATEGORIES+=		security

MAINTAINER=		filip@joyent.com
COMMENT=		PHP oauth consumer extension
LICENSE=		modified-bsd

USE_LANGUAGES=		c c++

.include "../../lang/php/ext.mk"
.include "../../www/curl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
