# $NetBSD: Makefile,v 1.4 2008/06/19 15:21:35 taca Exp $

DISTNAME=	rdiscount-1.3.4
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc

MAINTAINER=	filip@joyent.com
HOMEPAGE=	http://github.com/rtomayko/rdiscount/
COMMENT=	Discount is an implementation of John Gruber's Markdown markup language in C.

GEM_BUILD=	gemspec

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
