$NetBSD: patch-config_elasticsearch.yml,v 1.3 2014/07/29 16:57:23 fhajny Exp $

Define various paths

--- config/elasticsearch.yml.orig	2014-07-23 13:43:31.000000000 +0000
+++ config/elasticsearch.yml
@@ -143,10 +143,12 @@
 # Path to directory containing configuration (this file and logging.yml):
 #
 #path.conf: /path/to/conf
+path.conf: @PKG_SYSCONFDIR@
 
 # Path to directory where to store index data allocated for this node.
 #
 #path.data: /path/to/data
+path.data: @ES_DBDIR@
 #
 # Can optionally include more than one location, causing data to be striped across
 # the locations (a la RAID 0) on a file level, favouring locations with most free
@@ -157,14 +159,17 @@
 # Path to temporary files:
 #
 #path.work: /path/to/work
+path.work: @ES_TMPDIR@
 
 # Path to log files:
 #
 #path.logs: /path/to/logs
+path.logs: @ES_LOGDIR@
 
 # Path to where plugins are installed:
 #
 #path.plugins: /path/to/plugins
+path.plugins: @ES_LIBDIR@/plugins
 
 
 #################################### Plugin ###################################
