# $NetBSD: Makefile,v 1.6 2008/09/18 12:42:47 taca Exp $

DISTNAME=	ruby-openid-2.1.6
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME:S/ruby-//}
CATEGORIES=	devel

MAINTAINER=	filip@joyent.com
HOMEPAGE=	http://openidenabled.com/ruby-openid/
COMMENT=	Ruby library for verifying and serving OpenID identities

GEM_BUILD=	gemspec

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
