# $NetBSD$
#

DISTNAME=	manta-1.0.1
CATEGORIES=	sysutils
MASTER_SITES=	#

MAINTAINER=	filip@joyent.com
HOMEPAGE=	https://github.com/joyent/node-manta
COMMENT=	Node.js SDK for Manta
LICENSE=	mit

.include "../../joyent/sdc-node/Makefile.common"
.include "../../mk/bsd.pkg.mk"
