# $NetBSD$
#

DISTNAME=	smartdc-7.0.0
CATEGORIES=	sysutils
MASTER_SITES=	#

MAINTAINER=	filip@joyent.com
HOMEPAGE=	https://github.com/joyent/node-smartdc
COMMENT=	Client SDK and CLI for the Joyent SmartDataCenter API
LICENSE=	mit

.include "../../joyent/sdc-node/Makefile.common"
.include "../../mk/bsd.pkg.mk"
