$NetBSD$

Fix dependencies.

--- deps/git2-curl-0.4.1/Cargo.toml.orig	2016-04-29 23:26:09.000000000 +0000
+++ deps/git2-curl-0.4.1/Cargo.toml
@@ -15,7 +15,7 @@ Intended to be used with the git2 crate.
 
 [dependencies]
 curl = "0.2"
-url = "1.0"
+url = "1.1.0"
 log = "0.3"
 git2 = { path = "..", version = "0.4" }
 
