$NetBSD$

Fix dependencies.

--- deps/flate2-0.2.13/Cargo.toml.orig	2016-01-24 18:53:48.000000000 +0000
+++ deps/flate2-0.2.13/Cargo.toml
@@ -17,12 +17,12 @@ streams.
 
 [dependencies]
 libc = "0.2"
-miniz-sys = { path = "miniz-sys", version = "0.1.7", optional = true }
+miniz-sys = { path = "miniz-sys", version = "0.1.7" }
 libz-sys = { version = "1.0", optional = true }
 
 [dev-dependencies]
 rand = "0.3"
 
 [features]
-default = ["miniz-sys"]
+default = []
 zlib = ["libz-sys"]
