$NetBSD$

Remove Windows bits.

--- Cargo.toml.orig	2016-05-21 01:52:38.000000000 +0000
+++ Cargo.toml
@@ -17,7 +17,6 @@ name = "cargo"
 path = "src/cargo/lib.rs"
 
 [dependencies]
-advapi32-sys = "0.1"
 crates-io = { path = "src/crates-io", version = "0.2" }
 crossbeam = "0.2"
 curl = "0.2"
@@ -30,7 +29,6 @@ fs2 = "0.2"
 git2 = "0.4"
 git2-curl = "0.4"
 glob = "0.2"
-kernel32-sys = "0.2"
 libc = "0.2"
 libgit2-sys = "0.4"
 log = "0.3"
@@ -43,12 +41,6 @@ tempdir = "0.3"
 term = "0.4.4"
 toml = "0.1"
 url = "1.1"
-winapi = "0.2"
-
-[dev-dependencies]
-hamcrest = "0.1"
-bufstream = "0.1"
-filetime = "0.1"
 
 [[bin]]
 name = "cargo"
