$NetBSD$

Fix dependencies.

--- deps/curl-0.2.19/Cargo.toml.orig	2016-05-02 05:21:26.000000000 +0000
+++ deps/curl-0.2.19/Cargo.toml
@@ -8,7 +8,7 @@ repository = "https://github.com/carller
 description = "Rust bindings to libcurl for making HTTP requests"
 
 [dependencies]
-url = ">= 0.5, < 2.0"
+url = "1.1.0"
 log = "0.3.0"
 libc = "0.2"
 curl-sys = { path = "curl-sys", version = "0.1.0" }
