$NetBSD$

Fix default paths.
--- config/elasticsearch.yml.orig	2014-03-25 15:38:22.000000000 +0000
+++ config/elasticsearch.yml
@@ -142,11 +142,11 @@
 
 # Path to directory containing configuration (this file and logging.yml):
 #
-# path.conf: /path/to/conf
+path.conf: @PKG_SYSCONFDIR@
 
 # Path to directory where to store index data allocated for this node.
 #
-# path.data: /path/to/data
+path.data: @ES_DBDIR@
 #
 # Can optionally include more than one location, causing data to be striped across
 # the locations (a la RAID 0) on a file level, favouring locations with most free
@@ -156,15 +156,15 @@
 
 # Path to temporary files:
 #
-# path.work: /path/to/work
+path.work: @ES_WRKDIR@
 
 # Path to log files:
 #
-# path.logs: /path/to/logs
+path.logs: @ES_LOGDIR@
 
 # Path to where plugins are installed:
 #
-# path.plugins: /path/to/plugins
+path.plugins: @PREFIX@/lib/elasticsearch/plugins
 
 
 #################################### Plugin ###################################
@@ -318,7 +318,7 @@
 #
 # 1. Disable multicast discovery (enabled by default):
 #
-# discovery.zen.ping.multicast.enabled: false
+discovery.zen.ping.multicast.enabled: false
 #
 # 2. Configure an initial list of master nodes in the cluster
 #    to perform discovery when new nodes (master or data) are started:
@@ -375,3 +375,7 @@
 #monitor.jvm.gc.old.warn: 10s
 #monitor.jvm.gc.old.info: 5s
 #monitor.jvm.gc.old.debug: 2s
+
+# Disable dynamic script
+# http://www.cve.mitre.org/cgi-bin/cvename.cgi?name=2014-3120
+script.disable_dynamic: true
