# $NetBSD$

SYSLOG_MOD=	sql
SYSLOG_MODDIR=	afsql
COMMENT=	Syslog-ng SQL module

.include "../../joyent/syslog-ng/Makefile.module"

.include "../../databases/libdbi/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
