# $NetBSD$
#

DISTNAME=	Math-Complex-1.56
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	math joyent
MASTER_SITES=	http://search.cpan.org/CPAN/authors/id/J/JH/JHI/

MAINTAINER=	filip@joyent.com
HOMEPAGE=	http://search.cpan.org/~jhi/Math-Complex-1.56/
COMMENT=	Complex numbers and associated mathematical functions

PERL5_PACKLIST=	auto/Math/Complex/.packlist
USE_LANGUAGES=	# none

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
