# $NetBSD$
#

PKGNAME=	p5-${DISTNAME}
DISTNAME=	Image-Math-Constrain-1.02
CATEGORIES=	graphics joyent
MASTER_SITES=	http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/

MAINTAINER=	filip@joyent.com
HOMEPAGE=	http://search.cpan.org/~adamk/Image-Math-Constrain-1.02/
COMMENT=	Scaling math used in image size constraining (such as thumbnails)

PERL5_PACKLIST= auto/Image/Math/Constrain/.packlist

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
