# $NetBSD$

DISTNAME=	httpclient-2.1.5.2
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	pedro@joyent.com
HOMEPAGE=	http://dev.ctor.org/httpclient
COMMENT=	Like libwww-perl for Ruby
LICENSE=        ruby-license


GEM_BUILD=	gemspec

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
