# $NetBSD$

CONFLICTS+=     zabbix24-[0-9]*

DEPENDS+=       zabbix22-agent>=${PKGVERSION_NOREV}:../../joyent/zabbix22-agent

META_PACKAGE=   yes

.include "Makefile.common"

.include "../../mk/bsd.pkg.mk"
