# $NetBSD$

DISTNAME=	scmgit-base-2.0
CATEGORIES=	meta-pkgs
MASTER_SITES=	# empty
DISTFILES=	# empty

MAINTAINER=	pkgsrc@joyent.com
COMMENT=	Meta-package for old 'scmgit-base', use 'git-base' instead

META_PACKAGE=	yes

DEPENDS+=	git-base-[0-9]*:../../devel/git-base

.include "../../mk/bsd.pkg.mk"
