# $NetBSD: Makefile,v 1.6 2008/09/18 12:42:47 taca Exp $

DISTNAME=	memcache-client-1.7.4
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	filip@joyent.com
HOMEPAGE=	http://seattlerb.rubyforge.org/memcache-client/
COMMENT=	A ruby client for Danga Interactive's memcached

GEM_BUILD=	gemspec

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
